#baseURL: https://violinsonata.site/
baseURL: https://violin0622.github.io/
theme: LeaveIt
title: Sonata for solo Violin
copyright: ''
paginate: 12
publishDir: docs
defaultContentLanguage: en
disqusShortname: ''
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: ''
hasCJKLanguage: true
languages:
  en:
    languageCode: en

Permalinks:
  post: "/:year/:filename"

menu:
  main:
  - identifier: post
    name: Post
    url: /post/
    weight: 10
  - identifier: categories
    name: Categories
    url: /categories/
    weight: 20
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 30
  - identifier: about
    name: About
    url: /about/
    weight: 40

params:
  author: Violin
  avatar: /image/avatar.jpg
  subtitle: violin's personal blog, recording life and tech.
  lisence: <a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/"
    target="_blank">CC BY-NC-ND 4.0</a>
  customCSS: []
  customJS: []
  dateFormatToUse: '2006-01-02'
  description: 'violin sonata'
  homeFullContent: false
  mainSections:
  - post
  keywords:
  - Hugo
  - blog
  logoTitle: Jane
  photoswipe: true
  rssFullContent: true
  since: 2017
  social:
    Github: "https://github.com/violin0622"
    Email: "violin0622@outlook.com"
  toc: true
rssLimit: 20
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
